### ISSUE TITLE
Rendering Text

### ISSUE THREAD

**Issue by Nolram12345** [PaoloMazzon/Vulkan2D#11]
Hello! I'm curious if there is some suggested way of rendering text using the renderer. I didn't see anything about it in the code - is there some straightforward manner to do it? Or is it better to use an external GUI library?

**Comment by PaoloMazzon** [comment]
Hi, there are a few ways but VK2D doesn't provide any way to render text specifically out of the box. That said, the examples in this repo all have text rendering and that is done in [debug.c](https://github.com/PaoloMazzon/Vulkan2D/blob/master/examples/debug.c#L15) and my engine that uses VK2D also has its own way to [load fonts](https://github.com/PaoloMazzon/Astro/blob/master/src/InternalBindings.c#L1021) and [render them](https://github.com/PaoloMazzon/Astro/blob/master/src/RendererBindings.c#L460). Hope that helps!

**Comment by Nolram12345** [comment]
Thank you for the suggestions! I think the debug font rendering may be a tad too simplistic for what I am looking for, but your game engine implementation seems a fair bit more helpful - though extracting it may be a quite sophisticated endeavour. Perhaps native text rendering is something to consider for the future?
Either way, thank you for the pointers and this amazing library!

**Comment by PaoloMazzon** [comment]
I have long considered adding SDF font support and maybe when I have more time to work on it I'll add it to VK2D, but as it stands generic font support is out of the scope of the project. My game engine's implementation is hard to read because its tightly coupled to the engine but realistically I just use stb_ttf to generate a bunch of characters on one texture. Either way, good luck with your project!
