### ISSUE TITLE
Pixel Scaling / DPI in VK2D

### ISSUE THREAD

**Issue by Nolram12345** [PaoloMazzon/Vulkan2D#16]
Hello! I was curious how (or if at all) VK2D handles pixel element positioning and DPI differences.
For example, I noticed that when I initialise VK2D on my 4K screen with a single square with a position of 5, 5 and then move that window over to a 1080p screen, the square is now only 3 or so pixels distanced from 0, 0. Is there some internal scaling already going on?
Do you have any recommendations for positioning & rendering objects in a resolution-independent manner?

Thank you!

**Comment by Nolram12345** [comment]
Turns out the scaling was actually done by SDL2, which performs some internal conversions on Windows when process DPI awareness is enabled.

**Comment by PaoloMazzon** [comment]
Hello, as you've stated SDL2 is the culprit, but you can do things like [`SetProcessDPIAware`](https://learn.microsoft.com/en-ca/windows/win32/api/winuser/nf-winuser-setprocessdpiaware?redirectedfrom=MSDN) to mitigate the problem, but it is recommended to deal with that in the application manifest on Windows. You can also set processor-controlled DPI scaling in the executables property (occasionally you would have to do that for older games on Steam, for example). I intend to add a sample manifest for VK2D projects in the future since I have had multiple people point this out now lol.
