### ISSUE TITLE
Cryptic abort when calling vk2dRendererInit

### ISSUE THREAD

**Issue by WasabiThumb** [PaoloMazzon/Vulkan2D#3]
Greetings! I love the idea of this project and wanted to use it myself. Full disclosure that I am using JNA, however I do not think this is the source of the issue as I get a similar error when building and running the example project.

I'm tracing the steps performed in the example project, which was working right up until I had to call vk2dRendererInit. The method never actually returns any error code, instead it prints out some debug info and then aborts:
```
Available layers: 
  - VK_LAYER_VALVE_steam_fossilize_64
  - VK_LAYER_VALVE_steam_overlay_64
  - VK_LAYER_VALVE_steam_overlay_32
  - VK_LAYER_VALVE_steam_fossilize_32
  - VK_LAYER_NV_optimus

Vulkan Enabled Extensions: 
 - VK_KHR_surface
 - VK_KHR_xlib_surface
 - VK_EXT_debug_report


Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```
I am using Arch Linux x86-64 (Kernel 5.18.5-zen1-1-zen), here are some relevant packages I have installed:
```
nvidia-dkms 515.48.07-2
vulkan-headers 1:1.3.217-1
sdl2 2.0.22-2
sdl2_image 2.6.1-1
```
I will try the same setup on Windows soon, though linux support is a high priority of mine.

Anyways, you are doing something great here and I would love to be a part of it! :) Any response is appreciated

**Comment by PaoloMazzon** [comment]
Hey sorry been busy and likely will continue to be for a bit. I get something similar on Windows but I assumed that it was my shoddy environment but apparently its not just me so I'll investigate the Windows issue first and then I'll take a look at building on Linux.

Thanks for pointing this out as well!

**Comment by PaoloMazzon** [comment]
Apologies for the super late reply, I took another look and have since compiled and got Vulkan2D running on my install of Ubuntu and I have some guesses for what's going on. I just fixed an issue where the Vulkan context was not being error checked, and the first thing that should be printed to `stdout` after listing the available extensions is whatever graphics card VK2D finds. Since that doesn't happen I'm thinking the Vulkan context isn't being properly initialized. I see you have the Vulkan headers installed but its possible you're missing the validation layers? If you don't have the validation layers installed that shouldn't be a problem but you have to disable `VK2D_ENABLE_DEBUG` in `VK2D/BuildOptions.h` if you don't have them installed.

**Comment by WasabiThumb** [comment]
Thanks for all the help back then, yes I can confirm that the validation layers were the problem. I've been using this pipeline for a personal project for a while now, but given that I will have to think about distribution eventually, I was wondering if there was anything else I should know. I see that ``BuildOptions.h`` no longer exists, so other than the usual compiler options, is there something I should be doing for release builds? As it stands it seems to run fine on Windows targets, even those that don't have any SDKs installed, but I don't believe validation layers are really a thing on Windows, or at least its not an advertised part of the SDK. Of course I'm linking a few DLLs at runtime but that's standard.

**Comment by PaoloMazzon** [comment]
Hey, I'm glad to hear you're using it. I've been fairly busy recently and haven't got the chance to work on this as much as I would like but to answer your question in short, I replaced `BuildOptions.h` with the [VK2DStartupOptions](https://github.com/PaoloMazzon/Vulkan2D/blob/877df33e173743c9e826a1c92c67ca83e894c99d/VK2D/Structs.h#L202) struct which is passed to [VK2DRendererInit](https://github.com/PaoloMazzon/Vulkan2D/blob/877df33e173743c9e826a1c92c67ca83e894c99d/VK2D/Renderer.h#L25). I did this largely because I use this library myself as a submodule and passing a struct argument was a lot easier than messing around with local modifications to a submodule. In general you just want your release builds to not have debug layers enabled, everything else is your own choice. You may find depending on what you're doing that increasing vram page size ever so slightly boosts performance but I wouldn't worry about that in most cases tbh. I would love to see whatever you're working on with this library as well when its complete!

**Comment by WasabiThumb** [comment]
> Hey, I'm glad to hear you're using it. I've been fairly busy recently and haven't got the chance to work on this as much as I would like but to answer your question in short, I replaced `BuildOptions.h` with the [VK2DStartupOptions](https://github.com/PaoloMazzon/Vulkan2D/blob/877df33e173743c9e826a1c92c67ca83e894c99d/VK2D/Structs.h#L202) struct which is passed to [VK2DRendererInit](https://github.com/PaoloMazzon/Vulkan2D/blob/877df33e173743c9e826a1c92c67ca83e894c99d/VK2D/Renderer.h#L25). I did this largely because I use this library myself as a submodule and passing a struct argument was a lot easier than messing around with local modifications to a submodule. In general you just want your release builds to not have debug layers enabled, everything else is your own choice. You may find depending on what you're doing that increasing vram page size ever so slightly boosts performance but I wouldn't worry about that in most cases tbh. I would love to see whatever you're working on with this library as well when its complete!

Thank you so much, and I'm flattered by your interest! I do intend for the engine to be FOSS but it's not quite where I need it to be for the world to see it. It really is just a thin layer on top of VK2D, as well as (copying you a bit) cute_headers for sound and c2, with fallback pipelines in AWT and ``javax.sound`` that are atrocious but functional. Between JNI and VK2D is some threading and buffering shenanigans so that the VK2D subprocess can basically just do it's own thing and I can kind of forget about it. Plus some abstraction for unity-like object trees and behavior scripts, and some fake parallax with a non-linear relationship to the Z axis, so that depth can exist naturally even if the camera is locked to a 2D plane. I'll definitely update my GitHub as I have more to show. 

I do have a lame screenshot verifying that c2 works, I should really make more demos. I seem to only do it when I'm forced to verify something works and then I throw it away
![image](https://github.com/PaoloMazzon/Vulkan2D/assets/29989488/8a3d2af5-3f58-4c53-b8c5-3e975aa08b65)
(Pixelation due to following the "retro style" example)
